import glob
import pandas as pd

def load_all_history():
    # 抓取所有符合 aqhi_history_20xx.csv 格式的檔案
    files = sorted(glob.glob("aqhi_history_20*.csv"))
    df_list = [pd.read_csv(f) for f in files]
    
    # 合併成一個大型 DataFrame 供 GAGNN 訓練
    full_df = pd.concat(df_list, ignore_index=True)
    return full_df
